[package]
name = "motto_core"
version = "0.1.0"
authors = ["Jesse Gibson <JesseTheGibson@gmail.com>"]
edition = "2018"

[dependencies]
termion = "^1.5.1"
uuid = { version = "^0.7.2", features = ["v4"] }
